title: Lượng Trần | Learn. Work. Grow.
description: a software engineer specializing in web application development, holding a Bachelor's degree in Information Technology from the Industrial University of Ho Chi Minh City (IUH)
